# Topics
topics = [
    "Activism",
    "AddictionSupport",
    "Animals and Pets",
    "Art",
    "Beauty and Makeup",
    "Business,Economics,and Finance",
    "Careers",
    "Cars and MotorVehicles",
    "Celebrity",
    "Crafts and DIY",
    "Crypto",
    "Culture,Race,and Ethnicity",
    "Ethics and Philosophy",
    "Family and Relationships",
    "Fashion",
    "Fitness and Nutrition",
    "Food and Drink",
    "Funny/Humor",
    "Gaming",
    "Gender",
    "History",
    "Hobbies",
    "Home and Garden",
    "InternetCulture and Memes",
    "Law",
    "Learning and Education",
    "Marketplace and Deals",
    "MatureThemes and AdultContent",
    "Medical and MentalHealth",
    "Mens Health",
    "Meta/Reddit",
    "Military",
    "Movies",
    "Music",
    "Outdoors and Nature",
    "Place",
    "Podcasts and Streamers",
    "Politics",
    "Programming",
    "Reading,Writing,and Literature",
    "Religion and Spirituality",
    "Science",
    "SexualOrientation",
    "Sports",
    "TabletopGames",
    "Technology",
    "Television",
    "TraumaSupport",
    "Travel",
    "Womens Health",
    "World News",
]
